site_name: Gigaflow vSwitch (GvS)
site_author: Annus Zulfiqar
copyright: Copyright &copy; 2025 NextGArch Lab, University of Michigan

watch:
  - material

nav:
  - Home: index.md
  # - Redirect (hidden): home.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Benchmarks: benchmarks.md
  - Technical Details: technical-deepdive.md
  - Contributing: contributing.md
  - References: publications.md

theme: 
  name: material
  custom_dir: material
  logo: assets/gf-icon-transparent-smaller.png
  favicon: assets/gf-icon-transparent-smaller.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tabs.sticky
    - content.tooltips
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - dark_mode

  palette: 
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
extra_css: 
  - styles/custom.css

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/file-pdf
      link: https://dl.acm.org/doi/10.1145/3676641.3716000
    - icon: fontawesome/brands/github
      link: https://github.com/gigaflow-vswitch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/annuszulfiqar/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/mshahbaz/mshahbaz.gitlab.io/-/wikis/home

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details  # Supports '!!!' syntax (for blocks like '!!! tip')
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.arithmatex  # Enables math rendering if required
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html